[game]
debug = true

[camera]
aperture_f_stops = 8.0
shutter_speed_s  = 0.008
sensitivity_iso  = 100.0

[[weapons]]
name = "Gun"
damage = 10
reload_delay = 0.4
bullet_speed = 20.0
bullet_distance = 100.0

[[weapons]]
name = "Shotgun"
damage = 35
reload_delay = 0.9
bullet_speed = 30.0
bullet_distance = 100.0

[[weapons]]
name = "Enemy"
damage = 8
reload_delay = 2.5
bullet_speed = 12.0
bullet_distance = 100.0

[[levels]]
rows = 7
cols = 5
enemy_density = 0.10 # percent
item_density = 0.02 # percent


[[levels]]
rows = 10
cols = 8
enemy_density = 0.15 # percent
item_density = 0.02 # percent


