[game]
debug = false

[maze]
rows = 4
cols = 8

[camera]
aperture_f_stops = 8.0
shutter_speed_s  = 0.008
sensitivity_iso  = 100.0


[[weapons]]
name = "Gun"
damage = 10
bullet_speed = 20.0
reload_delay = 0.4

[[weapons]]
name = "Shotgun"
damage = 35
bullet_speed = 30.0
reload_delay = 0.9