[game]
debug = true

[camera]
aperture_f_stops = 8.0
shutter_speed_s  = 0.008
sensitivity_iso  = 100.0

[[weapons]]
name = "Gun"
damage = 10
reload_delay = 0.4
[weapons.bullet_config]
speed = 20.0
distance = 100.0
radius = 0.05 
length = 0.15 

[[weapons]]
name = "Shotgun"
damage = 35
reload_delay = 0.9
[weapons.bullet_config]
speed = 30.0
distance = 100.0
radius = 0.08 
length = 0.2 

[[weapons]]
name = "Enemy"
damage = 8
reload_delay = 2.5
[weapons.bullet_config]
speed = 12.0
distance = 100.0
radius = 0.4 
length = 0.4 

[[levels]]
rows = 7
cols = 5
enemy_density = 0.10 # percent
item_density = 0.02 # percent
enemy_bonus = 1.0

[[levels]]
rows = 10
cols = 8
enemy_density = 0.13 # percent
item_density = 0.02 # percent
enemy_bonus = 1.3

[[levels]]
rows = 12
cols = 10
enemy_density = 0.18 # percent
item_density = 0.02 # percent
enemy_bonus = 1.6

